title: Team TomoriNao
description: Team TomoriNao's official site
author: TomoriNao
baseurl: ""
url: "https://tomorinao.pro"
twitter:
  username: tomorinao_pro

markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - CNAME
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
